### ISSUE TITLE
Can you provide trained model for quick test?

### ISSUE THREAD

**Issue by devalexqt** [HighVoltageRocknRoll/sr#2]
Can you please provide trained model for quick start or input-> output result example? (video or image)

**Comment by HighVoltageRocknRoll** [comment]
> Can you please provide trained model for quick start or input-> output result example? (video or image)

There are checkpoints with trained weights for each model.

**Comment by Witiko** [comment]
In case @HighVoltageRocknRoll's explanation weren't entirely clear, the process for extracting models out of the checkpoints is as follows:
```
$ python generate_header_and_model.py --model=espcn --ckpt_path=checkpoints/espcn
$ python generate_header_and_model.py --model=srcnn --ckpt_path=checkpoints/srcnn
$ python generate_header_and_model.py --model=vespcn --ckpt_path=checkpoints/vespcn
$ python generate_header_and_model.py --model=vsrnet --ckpt_path=checkpoints/vsrnet
```
This should create the following model files, where `.pb` are tensorflow models and `.model` are native ffmpeg models. Since tensorflow can load both `.pb` and `.model` files, the latter seem more future-proof:
```
$ ls *.pb *.model
espcn.model  espcn.pb  srcnn.model  srcnn.pb  vespcn.model  vespcn.pb  vsrnet.model  vsrnet.pb
```
In my case, the produced `.model` files were not compatible with ffmpeg. Luckily, there is a script in the ffmpeg Git repository, which can correctly extract `.model` files out of `.pb` files:
```
$ git clone https://git.ffmpeg.org/ffmpeg.git
$ python ffmpeg/tools/python/convert.py --infmt tensorflow --outdir . espcn.pb
$ python ffmpeg/tools/python/convert.py --infmt tensorflow --outdir . srcnn.pb
$ python ffmpeg/tools/python/convert.py --infmt tensorflow --outdir . vespcn.pb
$ python ffmpeg/tools/python/convert.py --infmt tensorflow --outdir . vsrnet.pb
```
Now you can use the models in ffmpeg using [the `sr=model=espcn.model:dnn_backend=tensorflow option:scale_factor=2` video filter](https://ffmpeg.org/ffmpeg-filters.html#sr-1). Hope this helps!

**Comment by Witiko** [comment]
@devalexqt The process for extracting models out of the checkpoints is as follows:
```
$ python generate_header_and_model.py --model=espcn  --ckpt_path=checkpoints/espcn
$ python generate_header_and_model.py --model=srcnn  --ckpt_path=checkpoints/srcnn
$ python generate_header_and_model.py --model=vespcn --ckpt_path=checkpoints/vespcn
$ python generate_header_and_model.py --model=vsrnet --ckpt_path=checkpoints/vsrnet
```
This should create the following model files, where `.pb` are tensorflow models and `.model` are native ffmpeg models. Since tensorflow can load both `.pb` and `.model` files, the latter seem more future-proof:
```
$ ls *.pb *.model
espcn.model  espcn.pb  srcnn.model  srcnn.pb  vespcn.model  vespcn.pb  vsrnet.model  vsrnet.pb
```
In my case, the produced `.model` files were not compatible with ffmpeg. Luckily, there is a script in the ffmpeg Git repository, which can correctly extract `.model` files out of `.pb` files:
```
$ git clone https://git.ffmpeg.org/ffmpeg.git
$ python ffmpeg/tools/python/convert.py --infmt tensorflow --outdir . espcn.pb
$ python ffmpeg/tools/python/convert.py --infmt tensorflow --outdir . srcnn.pb
$ python ffmpeg/tools/python/convert.py --infmt tensorflow --outdir . vespcn.pb
$ python ffmpeg/tools/python/convert.py --infmt tensorflow --outdir . vsrnet.pb
```
Now you can use the models in ffmpeg using [the `sr=model=espcn.model` video filter](https://ffmpeg.org/ffmpeg-filters.html#sr-1). See https://github.com/HighVoltageRocknRoll/sr/issues/6 if you encounter speed issues.

**Comment by Witiko** [comment]
@HighVoltageRocknRoll Would it be possible to include the (tiny) .model files with the ffmpeg release or at least release the .model files here at GitHub? Ordinary users of ffmpeg who are not proficient in Python and ML would likely appreciate one less arcane step on their path to superresolution.
